### ISSUE TITLE
A lot of problems since the last few updates(see description)

### ISSUE THREAD

**Issue by drzeeb** [n-gao/LegionTD-Reborn#131]
Hi,

since the last 3 updates, I have a lot problems ingame.
At first, when I join, I can't see my towers on the panel, so I have to rejoin.
Than I don't see my tower value, tango income and gold income
![img_20181216_183006](https://user-images.githubusercontent.com/11742001/50057316-f75ffb80-0168-11e9-901d-63fbec1ad289.jpg)

Next problem is, I don't see my current tango and my food.

![img_20181216_183341](https://user-images.githubusercontent.com/11742001/50057330-0fd01600-0169-11e9-9624-892f72339588.jpg)

On the picture there should be the food be shown as  6/10 not as 0/10
and the Tango displays always zero.
Next problem is, when i upgrade the tower speed. The tower doesn't get faster.
Last problem is, that I don't get gold, when my team wins the duel.

I use archlinux for playing dota.

If I can provide you logs or something else, tell me.

Greetings CHARLIE WAFFLES

PS: The description field on n-gao.de has a maximum of 512 characters

**Comment by n-gao** [comment]
Thanks for reporting. This should be fixed with the latest update. Please reopen this issue if not.
