### ISSUE TITLE
Random builder sometimes doesn't get a 5th skill

### ISSUE THREAD

**Issue by patchandthat** [n-gao/LegionTD-Reborn#16]
Had it happen multiple times, not sure of exact repro steps as yet.

http://steamcommunity.com/sharedfiles/filedetails/?id=803380974

**Comment by n-gao** [comment]
did you start without discover spell?

**Comment by patchandthat** [comment]
No, I started with all 5 discover spells, but the 5th spell one didn't give a tower to build when used, just turned into a blank space.

**Comment by n-gao** [comment]
Ok, thank you!
I will fix that as soon as I get home.

**Comment by n-gao** [comment]
fixed with commit #402 thank you 👍
