### ISSUE TITLE
My statistics has been cleared

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#20]
Hi. My nickname is **Dizzy**
Today my statistics has been cleared in "won games" and "earned tango"
I was top2 and top1
And when im starting new game i am always level 0
Fix it please

**Comment by n-gao** [comment]
Im very sorry for that!!!
My last backup is from 22.December and I dont know where the bug is.

I will reset yours to my last backup.
Sadly I dont have time to fix the bug for the next few weeks.

**Comment by Dizzy76** [comment]
i can do screenshot 
i can see my real statistic for a second when i change tabs

**Comment by n-gao** [comment]
please do so

**Comment by Dizzy76** [comment]
![1](https://cloud.githubusercontent.com/assets/25136162/21964589/5f56c42e-db57-11e6-9d4d-5d92f0aa53d5.jpg)

**Comment by n-gao** [comment]
They then overwrite to 0?

**Comment by Dizzy76** [comment]
no
i played 1 game and now it 6

**Comment by Dizzy76** [comment]
level 6

**Comment by n-gao** [comment]
I have no clue how your data can get lost, if you finished your game tell me and i will reset your data

**Comment by Dizzy76** [comment]
im not playing now
can you return my data back as it shown on screenshot?

**Comment by n-gao** [comment]
yeah

**Comment by n-gao** [comment]
give me a second

**Comment by n-gao** [comment]
restored

**Comment by Dizzy76** [comment]
level was restored
but i  still cant see myself in "won games" and "earned tango"
or i just should wait statistics sync?

**Comment by n-gao** [comment]
highscores should be recalculated tomorrow, tell me if it hasnt changed tomorrow

**Comment by Dizzy76** [comment]
ok ty man
