### ISSUE TITLE
problem with data part 2

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#21]
Hi
my level was resetted again.
But i was not removed from highscores **yet**.
Please fix it again.
The good news that i think i know the reason which led to this action.

**Comment by n-gao** [comment]
sorry to hear that, what causes the problem?

**Comment by n-gao** [comment]
I restored your data

**Comment by Dizzy76** [comment]
two games in  a row the mode "return to sender" was voted for
and i left the games during the strategy time
the week ago i did same thing and result was same

P.S. Perhaps your should delete this mode, All top players hate it coz noobs are voting for it and understand nothing what this mode means,

**Comment by n-gao** [comment]
Its not the mode, but I still found the issue thanks.

**Comment by n-gao** [comment]
Leaving a game isnt the best choice, that causes some trouble.
