### ISSUE TITLE
Round Insta-start

### ISSUE THREAD

**Issue by JusFuhFun** [n-gao/LegionTD-Reborn#26]
I dont know if this always happens between round 6-7, but when round 6 ends round 7 starts instantly with out respawning our defenders and then 1 team just dies to medusas

**Comment by Dizzy76** [comment]
its bug with skip
when the last man (8 out of 8) prees "skip" just with creep respawning

it does not depend on number of the round

**Comment by n-gao** [comment]
thanks for that info, fixed
