### ISSUE TITLE
Player has abandoned the game (notification)

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#28]
Can you add notification "Player has abandoned the game" **just in a moment when he did it**.
Coz now other players have no idea wait his reconnection or not.

**Comment by Dizzy76** [comment]
notification in green colour like DotA 2 for example

**Comment by n-gao** [comment]
I added a message when someone abandones, but I will only be displayed when the game is not paused due to technical limitations.
