### ISSUE TITLE
New bug with abandoning players

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#29]
When  someone disconnects/leaves during the game - the clock turnes to negative and round never ends... meaning the game is over. Could you please look into this issue. 
Thank you in advance

**Comment by Dizzy76** [comment]
fix it coz its unplayable now =(

**Comment by n-gao** [comment]
Sorry reverted my last commit. I will add a message for abandoned players in the future. I am very busy at the moment. But please continue to report bugs, I will fix them as soon as possible.
