### ISSUE TITLE
Bug with automatic win

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#31]
It happaned with me twice in a row on early levels when many people (but not complete team) left the game in a short time period.
1st time we ramained 1 vs 3
2nd - 2 vs 2

**Comment by Dizzy76** [comment]
And 3rd time when we remained 3 vs 1
4th time when we remained  3 vs 3
but always on early levels

**Comment by n-gao** [comment]
Did someone reconnect during the match?

**Comment by n-gao** [comment]
Did my last patch fixed it?

**Comment by Dizzy76** [comment]
I haven't faced with that bug any more
