### ISSUE TITLE
Bug with automatic win wasnt fixed

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#33]
It happened again
Again on early stage
Many people disconected/reconected
And its always RADIANT VICTORY

**Comment by n-gao** [comment]
Im gonna check that on sunday, thanks for reporting

**Comment by Dizzy76** [comment]
Today the full dire team had abandoned the game during the strategy time and the game was not  interrupted with automatic win at all.

**Comment by Dizzy76** [comment]
Fix this bug too please
1 or 2 people had abandoned the game during the strategy time and radiant team got automatic win
**Its always radiant victory**

**Comment by Dizzy76** [comment]
when are you going to fix it?

**Comment by n-gao** [comment]
Does it only happens during strategy time?

**Comment by Dizzy76** [comment]
i think so
but not sure

**Comment by n-gao** [comment]
I guess I fixed it, please create a new issue when the bug still occurs.
