### ISSUE TITLE
Counting stops during the pick time

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#34]
This bug has appeared after dota 2 update "Dark moon"
Time counting stops during the pick time
And you cant pick during this time
Often the counting starts after 17 sec (just from 13)
But sometimes it get stuck and game not starts
I think coz of this playercount went from 450 at any time of the day to 180

**Comment by Dizzy76** [comment]
and there is no voting time now

**Comment by Dizzy76** [comment]
are you going to FIX IT???????????????

**Comment by n-gao** [comment]
Im very busy at the moment and it looks like its a valve issue, so I will wait first, sorry.

**Comment by n-gao** [comment]
is it fixed?

**Comment by Dizzy76** [comment]
yes it fixed
thank you
