### ISSUE TITLE
Radiant victory again

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#37]
**It happened twice in a row today**.
1) Someone of dire team had not picked the builder during the pick time and he couldnt pick during the level one coz its impossible now (after  patch 7.00)
2) Naturally this guy  had abandoned the game (at level one before creeps spawn)  and radiant team got automatic win just in time when creeps must spawn.

I described you 2 bugs:
1) autimatic win of radiant team ( **its ALWAYS RADIANT VICTORY**)
2) impossibility to pick hero if you passed the pick time.

Fix it please.

**Comment by n-gao** [comment]
even when radiant leaves?

**Comment by Dizzy76** [comment]
No
if radiant leaves the game continues

**Comment by n-gao** [comment]
I removed the auto ending when a team leaves, is it working now?

**Comment by Dizzy76** [comment]
It will take time to check

**Comment by Dizzy76** [comment]
yes it fixed
