### ISSUE TITLE
Statistics/Ranking

### ISSUE THREAD

**Issue by Avi3ndha** [n-gao/LegionTD-Reborn#50]
Statistics appear to be working correctly, but the ranking system has not been updating properly and is now completely blank when you open the window.

Obviously a low priority issue..just wanted to make you aware.

**Comment by n-gao** [comment]
Server data is correct, so its just a display issue, I will have a closer look in march.
Thanks for reporting, please continue to do so!

**Comment by n-gao** [comment]
Nevermind fixed
