### ISSUE TITLE
Wave 19. Bug with bloodrage

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#52]
Wave 19
Bloodrage has the global heal aura.
All units on the map are under the heal aura of bloodrage

**Comment by n-gao** [comment]
how do you mean that?

**Comment by Dizzy76** [comment]
at wave 19
all units/towers got bloodrage ability

**Comment by Dizzy76** [comment]
I noticed My towers receive healing only if they kill bloodseekers (wave units)
it doesn't happen with killing income units

**Comment by Dizzy76** [comment]
Look at the screenshot
![2](https://cloud.githubusercontent.com/assets/25136162/23578045/1d6ce85a-00d6-11e7-9288-5f1e4e65c94c.jpg)

**Comment by Dizzy76** [comment]
I just noticed
I had built many blooddrinkers and at wave 30 the dragon-boss received great healing (almost 80% of its hp) from killing my units.

**Comment by Dizzy76** [comment]
I have understand how this skill works =)
its ok
sorry
