### ISSUE TITLE
Thunderwarrior

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#53]
Thunderwarrior is the least usable tower in this game.
Coz it costs too much and there is much better alternative.
His spell **Static Remnant** is often useless coz it makes images behind thunderwarrior back.

Thunderelemental is much better choice coz:
1) it costs less
2) do much more damage
3) you can uprade it to Thundergod (imba!!!)

You must balance these thunder guys.

**Comment by Dizzy76** [comment]
My propositions:
1) nerf thundergod
2) nerf thunderelemental

3) Make Thanderwarrior good damage dealer (like sharpshooter or mind slicer)
a) remove **Static Remnant**
b) add spell with microstun or slow (like Overload)
c) increase atack range

**Comment by n-gao** [comment]
rebalanced
