### ISSUE TITLE
Elemental Builder

### ISSUE THREAD

**Issue by jonaswox** [n-gao/LegionTD-Reborn#66]
Elemental Builder has gone crazy. 

With 710 tower value, 2 tides, 1 lina, 1 earthshaker, 1 (lvl1)void, and a zeus

U can make it past ~lvl 22

**Comment by Dizzy76** [comment]
Yeap
You may not be a good player You just have to remember build.

**Comment by Dizzy76** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25136162/23708652/566bfdd4-041f-11e7-9a28-3c155b371321.png)
On screen that build

**Comment by Dizzy76** [comment]
I think Zeus must be nerfed again
As a compensation for elemental builder You can buff earthgod (add him skill Toss, for axample)

**Comment by Dizzy76** [comment]
forget about tiny
nerf damage of **Arc Lightning** from 125 to 100
as a compensation for elemental builder:
- buff armor of naga from 0 to 3
- buff damage of razor a bit

**Comment by Dizzy76** [comment]
ty
cant close this topic

**Comment by n-gao** [comment]
I will rework the calculation of how stacks are distributed

**Comment by n-gao** [comment]
done, you can try it. I hope it is better now.

**Comment by Dizzy76** [comment]
I understood your idea its simplier and better now
Ty

**Comment by n-gao** [comment]
im glad you like it

**Comment by Dizzy76** [comment]
Close this topic
