### ISSUE TITLE
Problem with statistics

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#68]
Today the statistics is overwriting to 0 after every game
Roofkiller, did you disconnect us from statistics server?
Community is shocked
Its not intresting to play without statistics.
Please fix it.

**Comment by n-gao** [comment]
Seems to be a bug with memory managment, I restarted the server, should be fixed. (My PC is broken I am not able to fix the bug, I can only restart the server right now)

**Comment by Dizzy76** [comment]
Ty
It was fixed

P.S. Can we hope for your return to bugs fixing after solving the problem with your PC?

**Comment by Dizzy76** [comment]
too many crashes after 7,04 patch
