### ISSUE TITLE
Legion TD Bugs

### ISSUE THREAD

**Issue by zio7rich** [n-gao/LegionTD-Reborn#7]
-The king's atk is delayed, and mobs get few extra hits in.
-At the end the 31+ wave, the spawns are crazy and causes the game to crash.
-Could you remove food limit? (cant kill all the mobs even when I have MAXED everything)
-remove useless outside effects please. (for shit computers that lag, removing trees, cutting map smaller.. etc it helps)
-When a player leaves, the skip counter still counts for the player that left. so it is impossible to reach 8/8 skip votes

**Comment by n-gao** [comment]
1. fixed
2. What do you mean by that?
3. I will think about that
4. fixed

**Comment by zio7rich** [comment]
the second point. )) At a certain point the game can not handle the insane amount of mobs coming out. As soon as it hits the king, it d.c everyone from thegame.

**Comment by n-gao** [comment]
Well I dont know whether I can fix that, could be engine related
