### ISSUE TITLE
Stats =(

### ISSUE THREAD

**Issue by jonaswox** [n-gao/LegionTD-Reborn#70]
Stats are derping hard =(

**Comment by n-gao** [comment]
I will bugfix as soon as I get my PC repaired.

**Comment by jonaswox** [comment]
thanks - sad to hear pc is broke

**Comment by n-gao** [comment]
I got a broken motherboard delivered, waiting for replacement at the moment.

**Comment by jonaswox** [comment]
=( - shit happens, sadly. 

Am I correct to assume that progress is not saved at the moment?

**Comment by n-gao** [comment]
you are right, Valve changed the Http API, so the game can not communicate with my server.

**Comment by jonaswox** [comment]
they are changing to much, all the time... everything needs bugfixing all the time - why do they not realise =O, they are software company

**Comment by jonaswox** [comment]
must be big hassle for you...

**Comment by n-gao** [comment]
it got much worse since 7.00, since then mod developers just trying to adjust to all the changes valve does.

**Comment by jonaswox** [comment]
U cannot restart the stats server?

**Comment by n-gao** [comment]
Wont help because, it is buggy due to an error on gameservers.

**Comment by n-gao** [comment]
fixed

**Comment by jonaswox** [comment]
Such nice update! Thanks alot roofkiller!!!!!!!

Maybe average tangoes per game, would be a fun ranking. Thats the only one I can think of right now
