### ISSUE TITLE
Nature builder (balancing)

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#71]
1) Buff Bug
a) Geminate Attack - reduce cooldown for Big Bug to 5:
b) Geminate Attack -  reduce cooldown for Very Big Bug to 3.

2) Iron bear - reduce gold cost from 210 to 180
3) Shroom - increase gold cost from 230 to 250

**Comment by n-gao** [comment]
done

**Comment by Dizzy76** [comment]
ty
