### ISSUE TITLE
Highscores

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#77]
What will be in the highscores?
only rating?

**Comment by n-gao** [comment]
at the moment there is the new rating and the old scores.

**Comment by Dizzy76** [comment]
I think in leaderboard could be only new rating and nothing more (no any wins, earned tango and etc.)
But the leaderboard should be expanded to 25 players

**Comment by Dizzy76** [comment]
Now statistics isnt working

BUT you did the great job
Im glad that you found time and inspiration to do this.

P.S. Make win rate in percentages.

**Comment by n-gao** [comment]
I will have to do a lot of optimization. I am gonna do that next week (i do not have access to my pc during the holidays)

**Comment by jonaswox** [comment]
so it will be offline for next 4 days?

Btw maybe average tangoes per game is a fun ranking?

**Comment by n-gao** [comment]
Yes I am sorry for that.

At my current state, gold per minute and Tangos per minute have been added as rankings

**Comment by Dizzy76** [comment]
its working now

**Comment by n-gao** [comment]
I highly improved the server performance. But I removed experience and kills as rankings. I will add a few other in the future.

**Comment by Dizzy76** [comment]
Roofkiller
please add 10 hp to Militia.
Many people ask me for this request for a long time. With 10 addithinal hp 2 milithia can def wave 1 (now its almost imposible)
Ty in advance.
Sorry for offtop

**Comment by Dizzy76** [comment]
With new statistics ppl will come into game

**Comment by Dizzy76** [comment]
Some ppl with higher rating have worse rank than those who have a worse rating
![untitled](https://cloud.githubusercontent.com/assets/25136162/25102252/51e3e18a-23c0-11e7-8d65-2fc4ac52822b.png)

**Comment by n-gao** [comment]
The shown values are realtime. The order will be refreshed every day.

**Comment by Dizzy76** [comment]
You dont understand me.
Look at the screenshot
For example:
RANK **11** has RATING **1250**
RANK **12** has RATING **1202**
RANK **13** has RATING **1290**

Sorting by rating is incorrect

**Comment by n-gao** [comment]
I understand you. The ranking will be calculated once per day. So here is a little example: player A has 1400 at the start of a day and Player B 1380. So A will be higher ranked than B until the next ranking will be calculated. However the rating value that is shown is their realtime rating.

**Comment by Dizzy76** [comment]
Now I understand how it works

**Comment by Dizzy76** [comment]
win rates were not calculated
![untitled](https://cloud.githubusercontent.com/assets/25136162/25143374/d6cc2c6a-2472-11e7-8571-6c18878aebf0.jpg)
P.S. Can you fix old icon bug. (I mean empty icons of towers)

**Comment by Dizzy76** [comment]
after last update win rate 0%

**Comment by Dizzy76** [comment]
Roofkiller
I saw in the code that you added 10 hp to militia.
But for randombuilder Militia still has 105 hp.
Implement it please.
Ty in advance
