### ISSUE TITLE
Undead builder

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#79]
Roofkiller
As i remember Undead builder was almost ready
I even tested it in beta version
May you release it?
If you say "No" i will understand you.
Just people ask me for it all time

**Comment by n-gao** [comment]
I am currently working on my bachelor thesis., so I sadly dont have enough time to balance and polish the undeadbuilder. I do not want to release a unbalanced and highly unpolished builder like that.

**Comment by Dizzy76** [comment]
Undead builder was Necrophos? Do I remember correctly? I tested Necrophos and balancing wasnt too bad.
If problem only in balance I can help with it.
Games for new builder can be excluded from rating untill balancing will be completed
But if you too busy i wont bother you now.

**Comment by n-gao** [comment]
Sorry I do not have enough time to finish the undeadbuilder. In three months I will have enough leisure time in order to finish the builder. If you have some experience in modding, you could finish it too.

**Comment by Dizzy76** [comment]
I wish I could but modding its not for me.
Do you have time for little balancing in the near future.
Nothing hard only changing numbers

**Comment by n-gao** [comment]
Sorry I can not promise anything.
I will take a look whether I find time to fix a few things and polish undeadbuilder

**Comment by Dizzy76** [comment]
Look
the all balancing what the game needs now its to make Nature builder the competitive one.
Now its almost useless
The easiest way is to buff aggressively passive skill of builder
for example from 20 to 35
P.S Sorry for offtop
