### ISSUE TITLE
Duel bug

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#83]
One guy was disconected on wave 8 and reconected on wave 9
On the duel after wave 10 his units were displayed with the color of the enemy and
His units Just stood and did not fight
So the game was endless
![untitled](https://cloud.githubusercontent.com/assets/25136162/25772019/6696d1ac-3269-11e7-9463-b8983e58dc0e.jpg)

**Comment by Dizzy76** [comment]
there was antother accident
we were in the party
I was disconected during the connection time
after reconection i got into another team

**Comment by Dizzy76** [comment]
it happaned again with the one who was disconected - reconected
![untitled](https://cloud.githubusercontent.com/assets/25136162/25840683/6962aa4e-34a5-11e7-86d4-bf87b8d4a103.png)

**Comment by Dizzy76** [comment]
and it happened again today

**Comment by n-gao** [comment]
fixed
