### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by Dizzy76** [n-gao/LegionTD-Reborn#84]
There is blue screen between waves...its so horrible

![1](https://cloud.githubusercontent.com/assets/25136162/25961367/beeb9ae6-3682-11e7-8be2-6644a0bd732f.jpg)
![2](https://cloud.githubusercontent.com/assets/25136162/25961371/c20e54d4-3682-11e7-9fdd-784110d145ae.jpg)

**Comment by Dizzy76** [comment]
only when fog of war was switched on

**Comment by Laika9876** [comment]
Why do not I take statistics into account?
P. S Sorry offtop

**Comment by n-gao** [comment]
I did not understand the question
